"""empty message

Revision ID: 932c2624e44f
Revises: 588c6a495dd6
Create Date: 2024-04-12 13:59:24.816335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932c2624e44f'
down_revision = '588c6a495dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Phones', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
