"""empty message

Revision ID: 588c6a495dd6
Revises: 91a5d1a79e61
Create Date: 2024-04-11 01:47:14.130994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588c6a495dd6'
down_revision = '91a5d1a79e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Phones', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
