"""empty message

Revision ID: 91a5d1a79e61
Revises: c0bb8a54d66b
Create Date: 2024-04-11 01:46:02.041068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a5d1a79e61'
down_revision = 'c0bb8a54d66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_url', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Phones', schema=None) as batch_op:
        batch_op.drop_column('product_url')

    # ### end Alembic commands ###
